### ISSUE TITLE
[bug] ModuleNotFoundError: No module named 'lxml'

### ISSUE THREAD

**Issue by BDonnot** [e2nIEE/pandapower#2752]
### Bug report checklis

- [x] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [x] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [x] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

- [x] Reproduced the issue after updating with `pip install --upgrade pandapower` (or `git pull`)

- [x] Tried basic troubleshooting (if a bug/error) like restarting the interpreter and checking the pythonpath

### Reproducible Example

```python
import pandapower as pp
```

### Issue Description and Traceback

Error is:

```
>>> import pandapower as pp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "XXX/venv_39/lib/python3.9/site-packages/pandapower/__init__.py", line 18, in <module>
    from pandapower.runpm import *
  File "XXX/venv_39/lib/python3.9/site-packages/pandapower/runpm.py", line 8, in <module>
    from pandapower.converter.pandamodels.from_pm import read_ots_results, read_tnep_results
  File "XXX/venv_39/lib/python3.9/site-packages/pandapower/converter/__init__.py", line 5, in <module>
    from pandapower.converter.cim import *
  File "XXX/venv_39/lib/python3.9/site-packages/pandapower/converter/cim/__init__.py", line 6, in <module>
    from .cim2pp import from_cim
  File "XXX/venv_39/lib/python3.9/site-packages/pandapower/converter/cim/cim2pp/__init__.py", line 5, in <module>
    from . import converter_classes
  File "XXX/venv_39/lib/python3.9/site-packages/pandapower/converter/cim/cim2pp/converter_classes/__init__.py", line 1, in <module>
    from . import connectivitynodes, coordinates, externalnetworks, generators, impedance, lines, loads, shunts, switches, transformers, wards
  File "XXX/venv_39/lib/python3.9/site-packages/pandapower/converter/cim/cim2pp/converter_classes/connectivitynodes/__init__.py", line 1, in <module>
    from . import connectivityNodesCim16
  File "XXX/venv_39/lib/python3.9/site-packages/pandapower/converter/cim/cim2pp/converter_classes/connectivitynodes/connectivityNodesCim16.py", line 8, in <module>
    from pandapower.converter.cim.cim2pp import build_pp_net
  File "XXX/venv_39/lib/python3.9/site-packages/pandapower/converter/cim/cim2pp/build_pp_net.py", line 16, in <module>
    from .. import cim_classes
  File "XXX/venv_39/lib/python3.9/site-packages/pandapower/converter/cim/cim_classes.py", line 15, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

```

As in understand, your team removed the lxml requirement in version 3.2 (pip installs lxml when installing `pandapower<3.2`) but pandapower still requires it in the cim imports.

Multiple possible solutions:
- keep the lxml package optional and add try / catch ImportError when importing the CIM feature (preferred method, as the install of pandapower will no longer require some heavy dependencies)
- add back (explicitly) the lxml package as a requirements of pandapower

(NB: i did not tried with pip directly, but use `uv` to manage virtual environment)

### Expected Behavior

No error, as in previous pandapower version

### Installed Versions

* python version: python 3.9 and 3.13 (I did not test intermediate versions)

To copy paste into a clean venv (for python 3.9):

```
build==1.3.0
certifi==2025.10.5
charset-normalizer==3.4.4
deepdiff==8.6.1
geojson==3.2.0
idna==3.11
importlib_metadata==8.7.0
networkx==3.2.1
numpy==2.0.2
orderly-set==5.5.0
packaging==25.0
pandapower==3.2.0
pandas==2.3.3
pybind11==3.0.1
pyproject_hooks==1.2.0
python-dateutil==2.9.0.post0
pytz==2025.2
requests==2.32.5
scipy==1.13.1
six==1.17.0
tomli==2.3.0
tqdm==4.67.1
typing_extensions==4.15.0
tzdata==2025.2
urllib3==2.5.0
zipp==3.23.0
```

### Label

- [ ] Relevant labels are selected

**Comment by KS-HTK** [comment]
This issue is already known and should be fixed in the near future. (bugfix release)
Installing lxml will solve it. But my recommendation generally would be to avoid `import pandapower […]` usage and use `from pandapower import […]` which will also solve this issue when not using the converter module.

lxml is a requirement for the pandapower.converter module and has been moved to the converter optional dependencies in pyproject.toml. During this change it was overlooked that the converter is imported in the base __init__.py. The planned resolution is to remove the converter from the init as most user do not require it to be loaded.

**Comment by BDonnot** [comment]
Hello,

Sorry if this issue has already been posted and solved. I did not saw it.

The issue is that is used to work for 5 years at least. And now it does not. A missing dependencies is, in my opinion, an issue.

And I think (but I may be wrong here) that it is good practice to be able to use the package with a standard import like

```python
import pandapower as pp
```

And it's still perfectly feasible with optional packages in different ways.

For example, you can:
- not include part of your module with specific requirements at the top import (and people that wants the converter can still `from pandapower.converter import whatever` provided that it's installed)
- include, at the top module imports, some try / catch block around the  imports of all modules with optional dependencies (that's the solution I use for lightsim2grid or grid2op for example)

I don't want any converters in the CI of grid2op and lightsim2grid. And they broke due to a regression in pandapower: lxml used to be required and automatically installed. Now it's not anymore, which breaks the `import pandapower as pp`


Best

Benjamin

**Comment by stibu81** [comment]
I think the problem still persists. The culprit seems to be `pandapower.runpm` which is also imported in the main `__init__.py`. After installing the `develop` branch form GitHub, I get this:

```
>>> import pandapower
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.12/site-packages/pandapower/__init__.py", line 18, in <module>
    from pandapower.runpm import *
  File ".../.venv/lib/python3.12/site-packages/pandapower/runpm.py", line 8, in <module>
    from pandapower.converter.pandamodels.from_pm import read_ots_results, read_tnep_results
  File ".../.venv/lib/python3.12/site-packages/pandapower/converter/__init__.py", line 5, in <module>
    from pandapower.converter.cim import *
  File ".../.venv/lib/python3.12/site-packages/pandapower/converter/cim/__init__.py", line 6, in <module>
    from .cim2pp import from_cim
  File ".../.venv/lib/python3.12/site-packages/pandapower/converter/cim/cim2pp/__init__.py", line 5, in <module>
    from . import converter_classes
  File ".../.venv/lib/python3.12/site-packages/pandapower/converter/cim/cim2pp/converter_classes/__init__.py", line 1, in <module>
    from . import connectivitynodes, coordinates, externalnetworks, generators, impedance, lines, loads, shunts, switches, transformers, wards
  File ".../.venv/lib/python3.12/site-packages/pandapower/converter/cim/cim2pp/converter_classes/connectivitynodes/__init__.py", line 1, in <module>
    from . import connectivityNodesCim16
  File ".../.venv/lib/python3.12/site-packages/pandapower/converter/cim/cim2pp/converter_classes/connectivitynodes/connectivityNodesCim16.py", line 8, in <module>
    from pandapower.converter.cim.cim2pp import build_pp_net
  File ".../.venv/lib/python3.12/site-packages/pandapower/converter/cim/cim2pp/build_pp_net.py", line 16, in <module>
    from .. import cim_classes
  File ".../.venv/lib/python3.12/site-packages/pandapower/converter/cim/cim_classes.py", line 15, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

**Comment by heckstrahler** [comment]
runpm should be fixed in #2777

**Comment by stibu81** [comment]
Maybe I'm doing something wrong, but I still get the same error with the current develop branch. It seems that the line

```
from pandapower.converter.pandamodels.from_pm import read_ots_results, read_tnep_results
```

in `runpm.py` causes `__init__.py` in the converter subpackage to be called, leading to this problem.

**Comment by BDonnot** [comment]
Hello guys,

And sorry to interrupt again on this matter.

From the discussions of today, I think it would be beneficial for the community and pandapower users that you include in your ci a test that `import pandapower as pp` works fine when pandapower is simply installed with `pip install .` (from git)

If `import pandapower as pp` should not be used like this you can run `import pandapower.netwroks as pn` or `from pandapower import runpf` for example. And if possible anything that is supposed to be importable without lxml.

Thanks for this good work 😊

**Comment by heckstrahler** [comment]
with #2778 the init.py from converter does not import anything anymore.

**Comment by stibu81** [comment]
I confirm that I can now run `import pandapower` without any issues. (I also checked that `lxml` is *not* installed.) Thanks for the fix!
