### ISSUE TITLE
[bug] Load flows with simbench grids do not converge since version 3.2

### ISSUE THREAD

**Issue by marhofmann** [e2nIEE/pandapower#2832]
### Reproducible Example

```python
import pandapower as pp
import simbench as sb

net = sb.get_simbench_net('1-LV-urban6--0-sw')
pp.runpp(net)
```

### Issue Description and Traceback

I get this output when i run the reproducible example with pandapower versions > 3.2:

```
~\.venv\lib\site-packages\simbench\converter\csv_pp_converter.py:874: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_data[output_name] = pd.concat([output_data[output_name], input_data[
~\.venv\lib\site-packages\simbench\converter\csv_pp_converter.py:874: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_data[output_name] = pd.concat([output_data[output_name], input_data[
~\.venv\lib\site-packages\simbench\converter\csv_pp_converter.py:874: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_data[output_name] = pd.concat([output_data[output_name], input_data[
~\.venv\lib\site-packages\simbench\converter\csv_pp_converter.py:874: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_data[output_name] = pd.concat([output_data[output_name], input_data[
~\.venv\lib\site-packages\simbench\converter\csv_pp_converter.py:874: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  output_data[output_name] = pd.concat([output_data[output_name], input_data[
~\.venv\lib\site-packages\pandapower\pf\create_jacobian.py:27: RuntimeWarning: invalid value encountered in divide
  dVm_x, dVa_x = dSbus_dV_numba_sparse(Ybus.data, Ybus.indptr, Ybus.indices, V, V / abs(V), Ibus)
~\.venv\lib\site-packages\pandapower\pypower\newtonpf.py:512: MatrixRankWarning: Matrix is exactly singular
  dx = -1 * spsolve(J, F, permc_spec=permc_spec, use_umfpack=use_umfpack)
Traceback (most recent call last):
  File "~\core\simbench_issue.py", line 5, in <module>
    pp.runpp(net)
  File "~\.venv\lib\site-packages\pandapower\run.py", line 252, in runpp
    _powerflow(net, **kwargs)
  File "~\.venv\lib\site-packages\pandapower\powerflow.py", line 70, in _powerflow
    _ppci_to_net(result, net)
  File "~\.venv\lib\site-packages\pandapower\powerflow.py", line 174, in _ppci_to_net
    raise LoadflowNotConverged("Power Flow {0} did not converge after "
pandapower.auxiliary.LoadflowNotConverged: Power Flow nr did not converge after 10 iterations!
```

### Expected Behavior

If I downgrade pandapower to any version < 3.2 the load flow converges successfully!

### Installed Versions

* python version: 3.10 * pandas version:  2.3.3 * networkx version: 3.4.2 * scipy version: 1.15.3 * numpy version: 2.2.6 * packaging version: 25.0 * tqdm version: 4.67.1 * deepdiff version: 8.6.1 * Operating System name/version: Windows 11

**Comment by vogt31337** [comment]
@marhofmann , this issue is successfully solved in pp 3.3.0 and simbench 1.6.1, therefore I close this issue.

**Comment by marhofmann** [comment]
@vogt31337 The issue is not resolved! I still see the same issue with all versions since 3.2!

**Comment by vogt31337** [comment]
@marhofmann, try setting voltage_depend_loads=False. It seems to be an issue with the simbench data / csv converter. We are still investigating.
